version: "3.7"

services:
  postgres:
    build: postgres
    environment:
      POSTGRES_DB: osc_demo
      POSTGRES_USER: osc_user
      POSTGRES_PASSWORD: osc_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5434:5432"
    volumes:
      - test_db:/var/lib/postgresql/data
      - ./postgres/work:/docker-entrypoint-initdb.d/
      - ./postgres/tmp:/opt/postgres
    container_name: osc_pgsql

volumes:
  test_db:
    external: true